import { Outfit} from "next/font/google";
import '../../styles/globals.css';
import Navbar from "../../components/Navbar";


const outfit = Outfit({
  variable: "--font-Outfit",
  subsets: ["latin"],
});



export const metadata = {
  title: "Entertainment Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable}`}>
        <Navbar/>
        <div className="container">
        {children}
        </div>
      </body>
    </html>
  );
}
